apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customermanagementapi
    version: "2.0"
  name: customermanagementapi-v2
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customermanagementapi
      version: "2.0"
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: customermanagementapi
        version: "2.0"
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE
          value: "false"
        - name: DOTNET_USE_POLLING_FILE_WATCHER 
          value: "true"
        image: luukjp/customermanagementapi:2.0
        imagePullPolicy: Always
        name: customermanagementapi
        ports:
        - containerPort: 5100
      restartPolicy: Always
---
