apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reviewmanagementapi
    version: "1.0"
  name: reviewmanagementapi
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviewmanagementapi
      version: "1.0"
  template:
    metadata:
      labels:
        app: reviewmanagementapi
        version: "1.0"
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE
          value: "false"
        - name: DOTNET_USE_POLLING_FILE_WATCHER 
          value: "true"
        image: luukjp/reviewmanagementapi:1.0
        imagePullPolicy: Always
        name: reviewmanagementapi
        ports:
        - containerPort: 5500
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: reviewmanagementapi
  name: reviewmanagementapi
  namespace: pitstop
spec:
  type: NodePort
  ports:
  - name: "http-5500"
    port: 5500
    targetPort: 5500
    nodePort: 30010
  selector:
    app: reviewmanagementapi
