apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: timeservice
    version: "1.0"
  name: timeservice
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timeservice
      version: "1.0"
  template:
    metadata:
      labels:
        app: timeservice
        version: "1.0"
    spec:
      containers:
      - env:
        - name: DOTNET_ENVIRONMENT
          value: Production
        - name: DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE
          value: "false"
        - name: DOTNET_USE_POLLING_FILE_WATCHER 
          value: "true"
        image: luukjp/timeservice:1.0
        imagePullPolicy: Always
        name: timeservice
      restartPolicy: Always
