apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: invoiceservice
  name: invoiceservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: invoiceservice
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: invoiceservice
    spec:
      containers:
        - env:
            - name: DOTNET_ENVIRONMENT
              value: Production
          image: pitstop/invoiceservice:1.0
          name: invoiceservice
      restartPolicy: Always
