apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: logserver
  name: logserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logserver
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: logserver
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
          image: datalust/seq:latest
          name: logserver
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
