apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: mailserver
  name: mailserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mailserver
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: mailserver
    spec:
      containers:
        - image: maildev/maildev:1.1.0
          name: mailserver
          ports:
            - containerPort: 25
              protocol: TCP
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
