apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: workshopmanagementapi
  name: workshopmanagementapi
spec:
  ports:
    - name: "5200"
      port: 5200
      targetPort: 5200
  selector:
    io.kompose.service: workshopmanagementapi
