apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: workshopmanagementapi
  name: workshopmanagementapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: workshopmanagementapi
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: workshopmanagementapi
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
          image: pitstop/workshopmanagementapi:1.0
          name: workshopmanagementapi
          ports:
            - containerPort: 5200
              protocol: TCP
      restartPolicy: Always
